[package]
name = "model-write-derive"
edition = "2018"
version = "0.0.1"
authors = ["Martin Smith <mcodesmith@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0" , features = ["parsing"]}
quote = "1.0"
proc-macro2 = "^1.0"
async-trait = "^0.1.50"
#arangors = "^0.4"
